---
title: "HW 4"
author: "Zilu Sun"
date: "Fall 2024"
output:
  pdf_document:
    latex_engine: xelatex

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## (a)

```{r}
library(data.table)
read_buoy_data <- function(year) {
  file_root <- "https://www.ndbc.noaa.gov/view_text_file.php?filename=44013h"
  tail <- ".txt.gz&dir=data/historical/stdmet/"
  path <- paste0(file_root, year, tail)
  header <- tryCatch(scan(path, what = 'character', nlines = 1), error = function(e) NULL)
  if (is.null(header)) return(NULL)
  skip_value <- ifelse(year < 2007, 1, 2)
  buoy <- fread(path, header = FALSE, skip = skip_value, fill = TRUE)
  buoy[, Year := year]
  if (year == 2000) {
    buoy <- cbind(buoy, NA)
    header <- c(header, "new_column") 
  }
  if (ncol(buoy) < length(header)) {
    missing_cols <- length(header) - ncol(buoy)
    buoy <- cbind(buoy, matrix(NA, nrow = nrow(buoy), ncol = missing_cols))
  }
  colnames(buoy) <- c(header, "Year")[1:ncol(buoy)]
  
  return(buoy)
}
years <- 1985:2023
buoy_data_list <- lapply(years, read_buoy_data)
all_buoy_data_2 <- rbindlist(buoy_data_list, use.names = TRUE, fill = TRUE)
```

## (b)

```{r}
missing_summary_999 <- sapply(all_buoy_data_2, function(x) sum(x == 999, na.rm = TRUE))
print(missing_summary_999)
missing_summary_99 <- sapply(all_buoy_data_2, function(x) sum(x == 99, na.rm = TRUE))
print(missing_summary_99)

all_buoy_data_2$ATMP<-ifelse(all_buoy_data_2$ATMP == 999,NA, 
                             all_buoy_data_2$ATMP)
all_buoy_data_2$MWD<-ifelse(all_buoy_data_2$MWD == 999,NA, 
                            all_buoy_data_2$MWD)
all_buoy_data_2$APD<-ifelse(all_buoy_data_2$APD == 99,NA, 
                            all_buoy_data_2$APD)
all_buoy_data_2$DPD<-ifelse(all_buoy_data_2$DPD == 99,NA, 
                            all_buoy_data_2$DPD)
all_buoy_data_2$WVHT<-ifelse(all_buoy_data_2$WVHT == 99,NA, 
                             all_buoy_data_2$WVHT)
all_buoy_data_2$DEWP<-ifelse(all_buoy_data_2$DEWP == 999,NA,
                             all_buoy_data_2$DEWP)
all_buoy_data_2$VIS<-ifelse(all_buoy_data_2$VIS == 99,NA, 
                            all_buoy_data_2$VIS)

buoy_clean <- all_buoy_data_2
library(dplyr)
missing_summary <- buoy_clean %>%
  select(-c(YY, `#YY`,DD, MM, YYYY, new_column,Year)) %>%
  summarise(across(everything(), ~mean(is.na(.), na.rm = TRUE)))
print(missing_summary)
library(tidyr)
missing_long <- gather(missing_summary, key = "variable", 
                       value = "missing_percentage")
library(ggplot2)
ggplot(missing_long, aes(x = variable, y = missing_percentage)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Missing Values Percentage per Variable", 
       y = "Percentage of Missing Values", x = "Variable")

#Not all "999" and "99" need to be treated as missing values
#there are many cases where the true value is equal to 999 or 99
#As can be seen from the bar chart, VIS has the most missing values,
#and most variables contain missing values

columns_of_interest <- buoy_clean %>%
  select(VIS,TIDE,MWD,BAR, DEWP, WD,Year)

missing_summary_by_year <- columns_of_interest %>%
  group_by(Year) %>%
  summarise(across(everything(), ~mean(is.na(.), na.rm = TRUE)))
missing_long_by_year <- missing_summary_by_year %>%
  pivot_longer(cols = -Year, names_to = "variable", values_to = "missing_percentage")
ggplot(missing_long_by_year, aes(x = Year, y = missing_percentage, color = variable)) +
  geom_line() +
  labs(title = "Missing Values Percentage Over Time",
       y = "Percentage of Missing Values",
       x = "Year") +
  theme_minimal()
#According to the BAR chart, VIS,TIDE,MWD,BAR, DEWP and WD
#which had a large number of overall missing values
#were selected to plot the yearly change of the proportion of missing values
#and no obvious periodicity or trend was found


```

## (c)

```{r}

annual_avg_temp <- buoy_clean %>%
  group_by(Year) %>%
  summarise(avg_temp = mean(ATMP, na.rm = TRUE))

ggplot(annual_avg_temp, aes(x = Year, y = avg_temp)) +
  geom_line(color = "#E64B35") +
  geom_point(color = "#4DBBD5") + 
  geom_smooth(method = "loess", color = "#4DBBD5", se = FALSE) +
  labs(title = "Annual Average Temperature Trend",
       x = "Year",
       y = "Average Temperature (°C)") +
  theme_minimal()
#According to the linear graph of average temperature changes 
#and the fitted curve for each year, it can be seen that the temperature 
#has shown a slow fluctuating upward trend from 1985 to 2023

annual_avg_wd <- buoy_clean %>%
  group_by(Year) %>%
  summarise(avg_wd = mean(WD, na.rm = TRUE))

ggplot(annual_avg_wd, aes(x = Year, y = avg_wd)) +
  geom_line(color = "#E64B35") +
  geom_point(color = "#4DBBD5") + 
  geom_smooth(method = "loess", color = "#4DBBD5", se = FALSE) +
  labs(title = "Annual Average Wind Direction Trend",
       x = "Year",
       y = "Average Wind Direction (°)") +
  theme_minimal()
#From the graph, it can be observed that the wind direction angles 
#fluctuated significantly between 1985 and 2023, but there is no apparent trend

```
## (d)
## 
```{r}
library(lubridate)
library(dplyr)

rain_data <- read.csv("Rainfall.csv") 
rain_data$Date <- as.Date(rain_data$DATE, format = "%Y%m%d %H:%M") 
rain_data <- rain_data %>%
  mutate(Year = year(Date))
annual_rainfall <- rain_data %>%
  group_by(Year) %>%
  summarise(total_rainfall = sum(HPCP, na.rm = TRUE),
            rainfall_sd = sd(HPCP, na.rm = TRUE))
print(annual_rainfall)
ggplot(annual_rainfall, aes(x = Year, y = total_rainfall)) +
  geom_line(color = "#E64B35") +
  geom_point(color = "#4DBBD5") + 
  geom_smooth(method = "loess", color = "#4DBBD5", se = FALSE) +
  labs(title = "Annual Total Rainfall Trend",
       x = "Year",
       y = "Total Rainfall (mm)") +
  theme_minimal()


ggplot(annual_rainfall, aes(x = Year, y = rainfall_sd)) +
  geom_line(color = "#E64B35") +
  geom_point(color = "#4DBBD5") + 
  geom_smooth(method = "loess", color = "#4DBBD5", se = FALSE) +
  labs(title = "Annual Rainfall sd Trend",
       x = "Year",
       y = "Rainfall_sd") +
  theme_minimal()

#As can be seen from the above two plots, although the rainfall in Boston 
#did not show an obvious trend from 1985 to 2013
#the standard deviation of precipitation in each year showed a decreasing trend, 
#indicating that the precipitation in Boston from 1985 to 2013 had a tendency to be 
#evenly distributed throughout the year

```